name: API Key Usage Workflow

on: [push]

jobs:
  use_api_key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any additional command to install dependencies here, if necessary

      - name: Run Python Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python use_api.py
